config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :admins
  devise_for :users

  get    'users/search'       => 'users#search',   as: :users_search
  post   'users/:id/friend'   => 'users#friend',   as: :friend
  delete 'users/:id/unfriend' => 'users#unfriend', as: :unfriend
  get    'users/:id'          => 'users#show',     as: :user

  get 'movies/search'         => 'movies#search',  as: :movies_search
  get 'movies/:id'            => 'movies#show',    as: :movie

  resources :ratings
  resources :recommendations

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
end

app/controllers/movies_controller.rb
require 'httparty'

class MoviesController < ApplicationController
  before_action :authenticate_user!

  def show
    movie_url = 'http://api.rottentomatoes.com/api/public/v1.0/movies/'
    api_key    = Rails.application.secrets.rottentomatoes_api_key

    url = movie_url + params[:id].to_s + ".json?apikey=#{api_key}"
    movie_response = HTTParty.get(url)
    @movie_dict = JSON.parse(movie_response.body, symbolize_names: true)
    @rating = (
      Rating.find_by(rottentomatoes_id: params[:id], rater: current_user) ||
      Rating.new(rottentomatoes_id: params[:id], rater: current_user)
    )
    @friends = current_user.friends
  end

  def search
    search_url = 'http://api.rottentomatoes.com/api/public/v1.0/movies.json'
    api_key    = Rails.application.secrets.rottentomatoes_api_key

    if request.GET[:title]
      title = URI.encode(request.GET[:title])
      url = search_url + "?apikey=#{api_key}&q=#{title}&page_limit=10&page=1"
      rottentomatoes_response = HTTParty.get(url)
      response_dict = JSON.parse(rottentomatoes_response.body, symbolize_names: true)
      @movie_dicts = response_dict[:movies]
    else
      @movie_dicts = []
    end
  end
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/movies/_rating_form.html.erb
<%= simple_form_for @rating do |f| %>
    <% if @rating.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@rating.errors.count, "error") %> prohibited this rating from being saved:</h2>

            <ul>
                <% @rating.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <%= f.input :rottentomatoes_id, as: :hidden %>
    <%= f.input :rater_id, as: :hidden %>
    <%= f.collection_radio_buttons :rating,
          [
            [0, '0'],
            [1, '1'],
            [2, '2'],
            [3, '3'],
            [4, '4'],
            [5, '5'],
            [6, '6'],
            [7, '7'],
            [8, '8'],
            [9, '9'],
            [10, '10']
          ],
          :first,
          :last
    %>
    <%= f.button :submit %>
<% end %>

app/views/movies/_recommendation_form.html.erb
<h1>Recommend to:</h1>

<%= form_tag recommendations_path do %>
    <ul>
        <% @friends.each do |friend| %>
            <li>
                <%= check_box_tag "friend-#{friend.id}", friend.id %>
                <%= label_tag "friend-#{friend.id}", friend.email %>
            </li>
        <% end %>
    </ul>
    <%= hidden_field_tag 'rottentomatoes_id', params[:id] %>
    <%= submit_tag 'Submit' %>
<% end %>

app/views/movies/search.html.erb
<h1>Search</h1>
<%= form_tag movies_search_path, method: :get do %>
    <%= text_field_tag 'title' %>
    <%= submit_tag 'Submit' %>
<% end %>

<h1>Movies</h1>
<ul>
    <% @movie_dicts.each do |movie_dict| %>
        <li><%= link_to movie_dict[:title], movie_path(movie_dict[:id]) %></li>
    <% end %>
</ul>

app/views/movies/show.html.erb
<h1><%= @movie_dict[:title] %></h1>
<h2><%= @movie_dict[:year] %></h2>

<p>Ratings:</p>
<p>Critic Score: <%= @movie_dict[:ratings][:critics_score] %></p>
<p>Audience Score: <%= @movie_dict[:ratings][:audience_score] %></p>

<h2>Your Rating</h2>
<%= render 'rating_form' %>
<%= render 'recommendation_form' %>